version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::895381577289:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-1KX8MU8SNIB0X"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::895381577289:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-MUYQEH4NV815"
cloudformation_execution_role = "arn:aws:iam::895381577289:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-1HM8W4EFVE0ZU"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-1kgpdfxllvgns"
image_repository = ""
region = "us-east-2"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::895381577289:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-6T2YPR1XW8XF"
cloudformation_execution_role = "arn:aws:iam::895381577289:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-WXJ9YB0P2K9B"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-1ppq7djx0pdjs"
image_repository = ""
region = "us-east-2"
